analytics_path: analytics
check_repo_dirty: true
data_path: data
experiments_path: logs
indicators:
- class_name: Scalar
  is_print: true
  name: '*'
web_api:
web_api_frequency: 60
web_api_open_browser: true
web_api_verify_connection: true
